version: '2'
services:
  lagoon-server:
    image: lagoon-server
    ports:
        - "22089:22089"
    depends_on:
        - lagoon-postgres
    environment:
        - PGHOST=lagoon-postgres
        - PGPORT=5432
        - PGPASSWORD=lagoonserver
        - PGUSER=lagoonserver
        - PGSCHEMA=CmdlineTests
        - LAGOONSERVER_EXTRA_ARGS=--verbose
  lagoon-postgres:
    image: postgres
    environment:
        - POSTGRES_USER=lagoonserver
        - POSTGRES_PASSWORD=lagoonserver
        - POSTGRES_DB=pfizer
