name: "master"
on:
  push:
    branches: [ master ]
    ignore-paths:
      - 'docs/**'
      - 'examples/**'
      - '**.md'
      - 'LICENSE'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - id: vars
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        
    - uses: cachix/install-nix-action@v10
    - uses: cachix/cachix-action@v6
      with:
        name: tweag-lagoon
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    
    - name: nix-build and unit test lagoon components
      run: nix-build -A lagoon-server -A lagoon-cmdline -A rubylagoon -A pylagoon -A rlagoon
      
    - name: Build docker image tarballs
      run: |
        nix-build -A lagoonDocker.server -o "lagoon-server-${{ steps.vars.outputs.sha_short }}.tar.gz"
        nix-build -A lagoonDocker.client -o "lagoon-client-${{ steps.vars.outputs.sha_short }}.tar.gz"
    - name: Login to docker
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Load and tag docker images
      run: |
        docker load < "lagoon-server-${{ steps.vars.outputs.sha_short }}.tar.gz"
        docker load < "lagoon-client-${{ steps.vars.outputs.sha_short }}.tar.gz"
        docker tag lagoon-server:latest "tweag/lagoon-server:${{ steps.vars.outputs.sha_short }}"
        docker tag lagoon-server:latest "tweag/lagoon-server:latest"
        docker tag lagoon-client:latest "tweag/lagoon-client:${{ steps.vars.outputs.sha_short }}"
        docker tag lagoon-client:latest "tweag/lagoon-client:latest"
    - name: Push docker images to DockerHub
      run: |
        docker push tweag/lagoon-server:latest
        docker push "tweag/lagoon-server:${{ steps.vars.outputs.sha_short }}"
        docker push tweag/lagoon-client:latest
        docker push "tweag/lagoon-client:${{ steps.vars.outputs.sha_short }}"
        
