name: "master"
on:
  push:
    branches: [ master ]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - id: vars
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        
    - uses: cachix/install-nix-action@v10
    - uses: cachix/cachix-action@v6
      with:
        name: tweag-lagoon
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    
    - name: nix-build and unit test datalake components
      run: nix-build -A datalake-server -A datalake-cmdline -A rubydatalake -A pydatalake -A rdatalake
      
    - name: Build docker image tarballs
      run: |
        nix-build -A datalakeDocker.server -o "datalake-server-${{ steps.vars.outputs.sha_short }}.tar.gz"
        nix-build -A datalakeDocker.client -o "datalake-client-${{ steps.vars.outputs.sha_short }}.tar.gz"
    - name: Login to docker
      uses: azure/docker-login@v1
      with:
        login-server: index.docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Load and tag docker images
      run: |
        docker load < "datalake-server-${{ steps.vars.outputs.sha_short }}.tar.gz"
        docker load < "datalake-client-${{ steps.vars.outputs.sha_short }}.tar.gz"
        docker tag datalake-server:latest "tweag/datalake-server:${{ steps.vars.outputs.sha_short }}"
        docker tag datalake-server:latest "tweag/datalake-server:latest"
        docker tag datalake-client:latest "tweag/datalake-client:${{ steps.vars.outputs.sha_short }}"
        docker tag datalake-client:latest "tweag/datalake-client:latest"
    - name: Push docker images to DockerHub
      run: |
        docker push tweag/datalake-server:latest
        docker push "tweag/datalake-server:${{ steps.vars.outputs.sha_short }}"
        docker push tweag/datalake-client:latest
        docker push "tweag/datalake-client:${{ steps.vars.outputs.sha_short }}"
        
